# Generated by Django 5.1.6 on 2025-04-02 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('CNN', 'CNN'), ('HT', 'Hindustan Times'), ('TOI', 'Times of India'), ('NDTV', 'NDTV'), ('BBC', 'BBC'), ('HINDU', 'The Hindu'), ('IT', 'India Today')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('latest-headlines', 'Latest Headlines'), ('politics-global-affairs', 'Politics & Global Affairs'), ('business-finance', 'Business & Finance'), ('technology-innovation', 'Technology & Innovation')], max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
